sudo: false
language: c
addons:
  apt:
    packages:
      - ftjam
      - imagemagick
      - valgrind
install:
  - git clone https://github.com/sstephenson/bats.git
  - PATH=$PATH:$(pwd)/bats/bin
script:
  - jam
